PREFIX rdf:<http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX rdfs:<http://www.w3.org/2000/01/rdf-schema#>
PREFIX krweb:<http://www.krweb.org/>
SELECT ?phone
WHERE
{
	?student rdf:type  <http://www.krweb.org/#Student>.
	?student krweb:has_phone ?phone.
	?student krweb:has_age ?age.
	FILTER (?age>"23")
}