PREFIX rdf:<http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX rdfs:<http://www.w3.org/2000/01/rdf-schema#>
PREFIX krweb:<http://www.krweb.org/>
SELECT ?name 
WHERE
{
	?professor rdf:type  <http://www.krweb.org/#Professor>.
	?professor krweb:member_of ?dep.
	?dep krweb:dep_city "Patra".
	?professor krweb:has_name ?name.
}
